version: "3.9"

services:
  # -------------------------------
  # 👩‍💻 API DEV
  # -------------------------------
  api_dev:
    build:
      context: .
      target: dev
    container_name: pokedex_api_dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis

  # -------------------------------
  # 🚀 API PROD
  # -------------------------------
  api_prod:
    build:
      context: .
      target: prod
    container_name: pokedex_api_prod
    ports:
      - "8080:8000"
    env_file: .env
    depends_on:
      - postgres
      - redis

  # -------------------------------
  # 🐘 PostgreSQL
  # -------------------------------
  postgres:
    image: postgres:16-alpine
    container_name: pokedex_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # -------------------------------
  # 🔴 Redis
  # -------------------------------
  redis:
    image: redis:7-alpine
    container_name: pokedex_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # -------------------------------
  # 📊 Exporters + Observabilité
  # -------------------------------
  redis_exporter:
    image: oliver006/redis_exporter:v1.62.0
    container_name: redis_exporter
    command: ["--redis.addr=redis://redis:6379"]
    ports:
      - "9121:9121"
    depends_on:
      - redis

  postgres_exporter:
    image: bitnami/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_URI: "postgres:5432/${POSTGRES_DB}?sslmode=disable"
      DATA_SOURCE_USER: ${POSTGRES_USER}
      DATA_SOURCE_PASS: ${POSTGRES_PASSWORD}
    ports:
      - "9187:9187"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api_dev
      - redis_exporter
      - postgres_exporter

  grafana:
    image: grafana/grafana:11.1.4
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

# -------------------------------
# 📦 Volumes
# -------------------------------
volumes:
  pg_data:
  redis_data:
  grafana_data:
